app = "voccaria-staging-backend"
primary_region = "bom"

[env]
PORT = "5000"
NODE_ENV = "production"

[http_service]
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
force_https = false
internal_port = 5000
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
