services:
  nginx:
    ports:
      - "80:80"

  frontend:
    build:
      context: client/web-frontend
      dockerfile: Dockerfile
    env_file:
      - .env.staging

  backend:
    build:
      context: server/node-backend
      dockerfile: Dockerfile
    env_file:
      - .env.staging
