services:
  frontend:
    image: ghcr.io/rajibul-dev/voccaria-frontend:latest
    restart: unless-stopped
    env_file:
      - .env.staging
    ports:
      - "127.0.0.1:3001:5000"

  backend:
    image: ghcr.io/rajibul-dev/voccaria-backend:latest
    restart: unless-stopped
    env_file:
      - .env.staging
    ports:
      - "127.0.0.1:5001:5000"
