services:
  nginx:
    ports:
      - "80:80"

  frontend:
    dockerfile: Dockerfile
    env_file:
      - .env.staging

  backend:
    dockerfile: Dockerfile
    env_file:
      - .env.staging
