services:
  frontend:
    image: rajidev/voccaria-frontend:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:3000:5000"

  backend:
    image: rajidev/voccaria-backend:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:5000:5000"
