name: voccaria-core

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - voccaria-network

  frontend:
    build:
      context: client/web-frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    networks:
      - voccaria-network
    develop:
      watch:
        - action: sync
          path: ./client/web-frontend/
          target: /app/
          ignore:
            - node_modules/
            - .git/
            - dist/
            - build/

  backend:
    build:
      context: server/node-backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    depends_on:
      - db
    networks:
      - voccaria-network
    develop:
      watch:
        - action: sync
          path: ./server/node-backend/
          target: /app/
          ignore:
            - node_modules/
            - .git/
            - dist/
            - build/
            - tmp/

  db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: core-db-mongodb
    env_file:
      - .env.db-root-creds
      - .env.db-voccaria
    volumes:
      - ./db-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - core-db-mongodb-data:/data/db
    networks:
      - voccaria-network

volumes:
  core-db-mongodb-data:

networks:
  voccaria-network:
