FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN \
  if [ -f yarn.lock ]; then yarn run build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
  else echo "Lockfile not found." && exit 1; \
  fi

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
